---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
resources:
- name: env
  type: git
  source:
    uri: ((pipeline-repo))
    branch: master
- name: installation
  type: s3
  source:
    bucket: ((platform-automation-bucket))
    regexp: installation-(.*).zip
- name: platform-automation
  type: pivnet
  source:
    product_slug: platform-automation
    api_token: ((pivnet-refresh-token))
jobs:
- name: export-installation
  serial: true
  plan:
    - get: platform-automation-image
      resource: platform-automation
      params:
        globs: ["*image*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        globs: ["*tasks*.zip"]
        unpack: true
    - get: env
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_CA_CERT: ((credhub_ca_cert))
        CREDHUB_SERVER: https://192.168.50.6:8844
        PREFIX: /concourse/main/cayenne
      input_mapping:
        files: env
      output_mapping:
        interpolated-files: interpolated-env
    - task: export-installation
      image: platform-automation-image
      file: platform-automation-tasks/tasks/export-installation.yml
      params:
        OM_TARGET: ((opsman-url))
        OM_USERNAME: ((opsman-username))
        OM_PASSWORD: ((opsman-password))
        OM_SKIP_SSL_VALIDATION: true
        # OM_CA_CERT: ((om_ca_cert))
    - put: installation
      params:
        file: installation/installation-*.zip
